---
# tasks file for nginx

- name: Add Nginx APT repository key
  apt_key:
    url: 'http://nginx.org/keys/nginx_signing.key'
    state: present
  register: nginx_apt_key
  tags:
    - setup
    - nginx

- name: Update keyring
  when: nginx_apt_key.changed
  command: "apt-key update"
  tags:
    - setup
    - nginx
    - skip_ansible_lint

- name: Add Nginx APT repository
  apt_repository:
    repo: 'deb http://nginx.org/packages/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} nginx'
    update_cache: yes
    state: present
  tags:
    - setup
    - nginx

- name: Install Nginx Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nginx_packages }}"
  tags:
    - package
    - nginx

- name: Manage user accounts
  user:
    name: nginx
    groups: www-data
    append: yes
    state: present
    system: yes
  notify: restart nginx
  tags:
    - setup
    - nginx

- name: Delete default config
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  tags:
    - setup
    - nginx

- name: Create sites folders
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - sites-available
    - sites-enabled
  tags:
    - setup
    - nginx

- name: Create nginx sites
  when: nginx_sites | length > 0
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item | basename | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ nginx_sites }}"
  notify: reload nginx
  tags:
    - config
    - nginx

- name: Enable defined sites
  when: nginx_sites_enabled | length > 0
  file:
    path: "/etc/nginx/sites-enabled/{{ item }}"
    src: "/etc/nginx/sites-available/{{ item }}"
    state: link
  with_items:
    - "{{ nginx_sites_enabled }}"
  notify: reload nginx
  tags:
    - config
    - nginx

- name: Create config file
  template:
    src: "{{ nginx_config_file }}"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  tags:
    - config
    - nginx

- name: Start and enable Nginx
  service:
    name: nginx
    enabled: yes
    state: started
  tags:
    - service
    - nginx
